// DD::Image knob ids. The index is the addUserKnob type and must stay in this order.
export const KNOB_KINDS = [
  "obsolete",
  "string",
  "file",
  "int",
  "enumeration",
  "bitmask",
  "bool",
  "double",
  "float",
  "array",
  "channelMask",
  "channel",
  "xy",
  "xyz",
  "wh",
  "bbox",
  "size",
  "format",
  "color",
  "acolor",
  "tab",
  "custom",
  "pyscript",
  "textEditor",
  "transform2d",
  "spacer",
  "text",
  "help",
  "multiline",
  "axis",
  "uv",
  "box3",
  "script",
  "lookupCurves",
  "tooltip",
  "pulldown",
  "eyedropper",
  "range",
  "histogram",
  "keyer",
  "colorChip",
  "link",
  "scale",
  "multilineEval",
  "oneview",
  "multiview",
  "viewview",
  "pypulldown",
  "obsoleteGpu",
  "multiarray",
  "viewpair",
  "list",
  "python",
  "metadata",
  "pixelAspect",
  "cp",
  "toolbar",
  "tabGroup",
  "pluginPython",
  "exogroup",
  "menu",
  "password",
  "toolbox",
  "table",
  "geoSelect",
  "inputChannelMask",
  "inputChannel",
  "controlPointCollection",
  "cascadingEnumeration",
  "dynamicBitmask",
  "metaKeyFrame",
  "positionVector",
  "cachedFile",
  "transformJack",
  "ripple",
  "sceneView",
  "vspacer",
  "cancelExecution",
  "simpleArray",
  "resizableArray",
  "disable",
  "icon",
  "frameExtent",
  "radio",
  "freetype",
  "editableEnumeration",
  "colorspace",
  "particleChannels",
  "sceneGraph",
  "pathExpression",
  "path",
  "gsv",
  "blinkEditor",
  "vec2",
  "usdSceneGraph",
  "vec3",
  "vec4",
] as const;

export type KnobKind = (typeof KNOB_KINDS)[number];

export function knobKind(type: number): KnobKind {
  return KNOB_KINDS[type] ?? "string";
}

const INLINE_BY_DEFAULT = new Set<KnobKind>(["bool", "pyscript", "spacer", "text", "script", "vspacer"]);

export function startsNewLine(kind: KnobKind, explicit: boolean | null): boolean {
  if (explicit != null) return explicit;
  return !INLINE_BY_DEFAULT.has(kind);
}
